include: https://salsa.debian.org/salsa-ci-team/pipeline/raw/master/salsa-ci.yml

build:
    extends: .build-unstable

reprotest:
    extends: .test-reprotest
    # Until https://bugs.debian.org/912340 is fixed
    allow_failure: true

lintian:
    extends: .test-lintian

autopkgtest:
    extends: .test-autopkgtest

piuparts:
    extends: .test-piuparts
    image: registry.salsa.debian.org/sathieu/images/piuparts:patch-4
    script:
      - CHROOT_PATH=/tmp/debian-unstable
      - CONTAINER_ID=$(docker run --rm -d debian:unstable sleep infinity)
      - docker exec ${CONTAINER_ID} bash -c "apt-get update && apt-get install eatmydata -y"
      - mkdir -p ${CHROOT_PATH}
      - docker export ${CONTAINER_ID} | tar -C ${CHROOT_PATH} -xf -
      - mknod -m 666 ${CHROOT_PATH}/dev/urandom c 1 9
      - mkdir -p ${CHROOT_PATH}/etc-target/apt/sources.list.d ${CHROOT_PATH}/etc-target/apt/preferences.d
      - cp -aTv /etc/apt/sources.list.d  ${CHROOT_PATH}/etc-target/apt/sources.list.d
      - cp -aTv /etc/apt/preferences.d  ${CHROOT_PATH}/etc-target/apt/preferences.d
      - piuparts --scriptsdir /etc/piuparts/scripts --allow-database --warn-on-leftovers-after-purge --hard-link -e ${CHROOT_PATH} ${WORKING_DIR}/*.deb

# Samba sometimes needs ldb from experimental
before_script:
  - echo 'deb http://deb.debian.org/debian experimental main' > /etc/apt/sources.list.d/experimental.list
  - "echo 'Package: ldb-tools libldb* python*-ldb*\nPin: release a=experimental\nPin-Priority: 500' > /etc/apt/preferences.d/experimental.pref"
