include: https://salsa.debian.org/salsa-ci-team/pipeline/raw/master/salsa-ci.yml

build:
    extends: .build-package

reprotest:
    extends: .test-reprotest
    # Until https://bugs.debian.org/912340 is fixed
    allow_failure: true

lintian:
    extends: .test-lintian

autopkgtest:
    extends: .test-autopkgtest

piuparts:
    extends: .test-piuparts

# Samba sometimes needs ldb from experimental
before_script:
  - echo 'deb http://deb.debian.org/debian experimental main' > /etc/apt/sources.list.d/experimental.list
  - "echo 'Package: ldb-tools libldb* python*-ldb*\nPin: release a=experimental\nPin-Priority: 500' > /etc/apt/preferences.d/experimental.pref"
